CREATE TABLE "MASTER_ACCOUNT"
(
    "ID"            SERIAL PRIMARY KEY,
    "ACCOUNT_NUMBER" INTEGER        NOT NULL UNIQUE,
    "BALANCE"       NUMERIC(10, 2) NOT NULL
);

CREATE TABLE "SUB_ACCOUNT"
(
    "ID"            SERIAL PRIMARY KEY,
    "PARENT_ID"      INTEGER        NOT NULL,
    "ACCOUNT_NUMBER" INTEGER        NOT NULL UNIQUE,
    "BALANCE"       NUMERIC(10, 2) NOT NULL
);

CREATE TABLE "AUDIT_TRAIL"
(
    "ID"        SERIAL PRIMARY KEY,
    "MAKER"     TEXT                     NOT NULL,
    "CHECKER"   TEXT                     NOT NULL,
    "COMMENT"   TEXT                     NOT NULL,
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);