@Api_HostAddress = http://localhost:5050

### reset Account

POST {{Api_HostAddress}}/transaction/resetAccount
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJ1c2VyLWlkLTEyMyIsInVuaXF1ZV9uYW1lIjoiYWxpY2UiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwiZW1wbG95ZWVfc3RhdHVzIjoiQWN0aXZlIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3NjQ5NDU3MTcsImV4cCI6MjcxMTYzMDUxNywiaWF0IjoxNzY0OTQ1NzE3LCJpc3MiOiJZb3VySXNzdWVyIiwiYXVkIjoiWW91ckF1ZGllbmNlIn0.zAaGkWWYMJzsa9agdL4Ug9Q9FRTYdoCqjdojhPAJMPU
X-Api-Version: 1.0

{
  "MasterAccNum": 10000,
  "SubAccNum": 10001
}


### money transfer

POST {{Api_HostAddress}}/transaction/moneyTransfer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJ1c2VyLWlkLTEyMyIsInVuaXF1ZV9uYW1lIjoiYWxpY2UiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwiZW1wbG95ZWVfc3RhdHVzIjoiQWN0aXZlIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3NjQ5NDU3MTcsImV4cCI6MjcxMTYzMDUxNywiaWF0IjoxNzY0OTQ1NzE3LCJpc3MiOiJZb3VySXNzdWVyIiwiYXVkIjoiWW91ckF1ZGllbmNlIn0.zAaGkWWYMJzsa9agdL4Ug9Q9FRTYdoCqjdojhPAJMPU
X-Api-Version: 1.0

{
  "MasterAccNum": 10000,
  "SubAccNum": 10001,
  "Amount": 60,
  "FlagException": true
}

### accountBalance

POST {{Api_HostAddress}}/transaction/accountBalance
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJ1c2VyLWlkLTEyMyIsInVuaXF1ZV9uYW1lIjoiYWxpY2UiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwiZW1wbG95ZWVfc3RhdHVzIjoiQWN0aXZlIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3NjQ5NDU3MTcsImV4cCI6MjcxMTYzMDUxNywiaWF0IjoxNzY0OTQ1NzE3LCJpc3MiOiJZb3VySXNzdWVyIiwiYXVkIjoiWW91ckF1ZGllbmNlIn0.zAaGkWWYMJzsa9agdL4Ug9Q9FRTYdoCqjdojhPAJMPU
X-Api-Version: 1.0

{
  "MasterAccNum": 10000,
  "SubAccNum": 10001
}