@TodoApi_HostAddress = http://localhost:5083

GET {{TodoApi_HostAddress}}/api/todo
Accept: application/json

###


POST {{TodoApi_HostAddress}}/api/todo
Content-Type: application/json

{
  "Id": 1,
  "Name": "Jiandong",
  "IsComplete": true
}